// ===----------------------------------------------------------------------===//
//
// Part of the FullStaQD Project, under the Apache License v2.0 with LLVM
// Exceptions.
// See <repo-root>/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// ===----------------------------------------------------------------------===//

#include "qcc/Compiler/Pipeline.h"
#include "qcc/Dialect/Aux_/IR/Aux_.h"
#include "qcc/Dialect/Jasp/IR/Jasp.h"
#include "qcc/Support/Elf2Mem.h"

#include "mlir/Conversion/VectorToSCF/VectorToSCF.h"
#include "mlir/Dialect/Arith/Transforms/BufferizableOpInterfaceImpl.h"
#include "mlir/Dialect/Bufferization/Transforms/FuncBufferizableOpInterfaceImpl.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/Func/Extensions/InlinerExtension.h"
#include "mlir/Dialect/Linalg/Transforms/BufferizableOpInterfaceImpl.h"
#include "mlir/Dialect/MemRef/Transforms/AllocationOpInterfaceImpl.h"
#include "mlir/Dialect/MemRef/Transforms/Passes.h"
#include "mlir/Dialect/QC/IR/QCDialect.h"
#include "mlir/Dialect/SCF/Transforms/BufferizableOpInterfaceImpl.h"
#include "mlir/Dialect/Tensor/Transforms/BufferizableOpInterfaceImpl.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/DialectRegistry.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/InitAllDialects.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Target/LLVMIR/Dialect/Builtin/BuiltinToLLVMIRTranslation.h"
#include "mlir/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.h"
#include "mlir/Target/LLVMIR/Export.h"
#include "mlir/Tools/mlir-opt/MlirOptMain.h"

#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileUtilities.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"

// Generated by EmbedFile.cmake from hisepq.ld: defines `kHisepqLd` (bytes) and `kHisepqLdSize`.
#include "HisepqLd.inc"

namespace cl = llvm::cl;

static cl::OptionCategory qccCategory("QCC options");

using qcc::Stage;
using qcc::Target;

namespace {

/// Sets up the RISC-V target machine used for all --target=hisep-q native code generation
/// (assembly, object, and as a prerequisite for linking to ELF/mem).
std::unique_ptr<llvm::TargetMachine> createHisepQTargetMachine(llvm::Module& llvmModule, llvm::StringRef mtriple,
                                                               llvm::StringRef mattr) {
  LLVMInitializeRISCVTargetInfo();
  LLVMInitializeRISCVTarget();
  LLVMInitializeRISCVTargetMC();
  LLVMInitializeRISCVAsmPrinter();
  // The MC streamer needs an asm parser to lower the inline asm that ConvertQIRToIntrinsics emits
  // in `_start` (see emitStartFunc).
  LLVMInitializeRISCVAsmParser();

  std::string attrsStr = mattr.empty() ? "+experimental-xqv" : mattr.str();
  llvm::Triple triple(llvm::Triple::normalize(mtriple.empty() ? "riscv32-unknown-unknown" : mtriple.str()));

  std::string errorStr;
  const llvm::Target* theTarget = llvm::TargetRegistry::lookupTarget(/*MArch=*/"", triple, errorStr);
  if (theTarget == nullptr) {
    llvm::errs() << "could not find target '" << triple.str() << "': " << errorStr << "\n";
    return nullptr;
  }

  llvm::TargetOptions targetOptions;
  // hisepq.ld relies on each function living in its own `.text.<name>` section so it can pull
  // `.text.main` to the front of the image (execution starts at the hardware's boot address).
  targetOptions.FunctionSections = true;
  std::unique_ptr<llvm::TargetMachine> targetMachine(
      theTarget->createTargetMachine(triple, /*cpu=*/"", attrsStr, targetOptions, std::nullopt));

  llvmModule.setDataLayout(targetMachine->createDataLayout());
  llvmModule.setTargetTriple(triple);

  return targetMachine;
}

/// Runs the codegen passes required to emit `fileType` for `llvmModule` on `os`. Returns false
/// (after printing an error) on failure.
bool emitNativeFile(llvm::Module& llvmModule, llvm::TargetMachine& targetMachine, llvm::CodeGenFileType fileType,
                    llvm::raw_pwrite_stream& os) {
  llvm::legacy::PassManager codegenPM;
  if (targetMachine.addPassesToEmitFile(codegenPM, os, /*DwoOut=*/nullptr, fileType)) {
    llvm::errs() << "target machine cannot emit files of this type\n";
    return false;
  }
  codegenPM.run(llvmModule);
  return true;
}

/// Links `objPath` into an ELF image at `elfPath` using hisepq.ld (embedded into this binary, see
/// HisepqLd.inc), by shelling out to `linkerExe` (e.g. "ld.lld").
bool linkHisepQElf(llvm::StringRef linkerExe, llvm::StringRef objPath, llvm::StringRef elfPath) {
  llvm::ErrorOr<std::string> linkerPath = llvm::sys::findProgramByName(linkerExe);
  if (!linkerPath) {
    llvm::errs() << "error: could not find linker '" << linkerExe << "' on PATH (override with --linker)\n";
    return false;
  }

  llvm::SmallString<128> ldScriptPath;
  if (std::error_code ec = llvm::sys::fs::createTemporaryFile("hisepq", "ld", ldScriptPath)) {
    llvm::errs() << "error: could not create a temporary linker script: " << ec.message() << "\n";
    return false;
  }
  llvm::FileRemover ldScriptRemover(ldScriptPath);

  {
    std::error_code ec;
    llvm::raw_fd_ostream ldScriptFile(ldScriptPath, ec, llvm::sys::fs::OF_Text);
    if (ec) {
      llvm::errs() << "error: could not write the embedded linker script: " << ec.message() << "\n";
      return false;
    }
    ldScriptFile << llvm::StringRef(reinterpret_cast<const char*>(kHisepqLd), kHisepqLdSize);
  }

  llvm::SmallVector<llvm::StringRef> args = {*linkerPath, "-T", ldScriptPath, objPath, "-o", elfPath};
  std::string errMsg;
  int rc = llvm::sys::ExecuteAndWait(*linkerPath, args, /*Env=*/std::nullopt, /*Redirects=*/{},
                                     /*SecondsToWait=*/0, /*MemoryLimit=*/0, &errMsg);
  if (rc != 0) {
    llvm::errs() << "error: linking failed" << (errMsg.empty() ? "" : ": " + errMsg) << "\n";
    return false;
  }
  return true;
}

/// Implements --compile-to=elf and --compile-to=mem: translates `module` to LLVM IR, compiles it
/// to a RISC-V object file, links it with the embedded hisepq.ld, and -- for Stage::Mem -- converts
/// the resulting ELF into a Verilog $readmemh memory file. Only ever called for
/// --target=hisep-q.
int compileToElfOrMem(mlir::ModuleOp module, Stage stage, llvm::StringRef outputFilename, llvm::StringRef mtriple,
                      llvm::StringRef mattr, llvm::StringRef linkerExe) {
  llvm::LLVMContext llvmContext;
  std::unique_ptr<llvm::Module> llvmModule = mlir::translateModuleToLLVMIR(module, llvmContext);
  if (!llvmModule) {
    llvm::errs() << "failed to translate the module to LLVM IR\n";
    return 1;
  }

  std::unique_ptr<llvm::TargetMachine> targetMachine = createHisepQTargetMachine(*llvmModule, mtriple, mattr);
  if (!targetMachine) {
    return 1;
  }

  llvm::SmallString<128> objPath;
  if (std::error_code ec = llvm::sys::fs::createTemporaryFile("qcc", "o", objPath)) {
    llvm::errs() << "error: could not create a temporary object file: " << ec.message() << "\n";
    return 1;
  }
  llvm::FileRemover objRemover(objPath);

  {
    std::error_code ec;
    llvm::raw_fd_ostream objFile(objPath, ec, llvm::sys::fs::OF_None);
    if (ec) {
      llvm::errs() << "error: could not open a temporary object file: " << ec.message() << "\n";
      return 1;
    }
    if (!emitNativeFile(*llvmModule, *targetMachine, llvm::CodeGenFileType::ObjectFile, objFile)) {
      return 1;
    }
  }

  // The final ELF is either the user's requested output (Stage::Elf) or a scratch file we still
  // need to read back and convert (Stage::Mem).
  const bool isFinalElf = stage == Stage::Elf;
  llvm::SmallString<128> elfPath;
  llvm::FileRemover elfRemover;
  if (isFinalElf) {
    elfPath = outputFilename;
  } else {
    if (std::error_code ec = llvm::sys::fs::createTemporaryFile("qcc", "elf", elfPath)) {
      llvm::errs() << "error: could not create a temporary ELF file: " << ec.message() << "\n";
      return 1;
    }
    elfRemover.setFile(elfPath);
  }

  if (!linkHisepQElf(linkerExe, objPath, elfPath)) {
    return 1;
  }

  if (isFinalElf) {
    return 0;
  }

  llvm::ErrorOr<std::unique_ptr<llvm::MemoryBuffer>> elfBufferOrErr = llvm::MemoryBuffer::getFile(elfPath);
  if (std::error_code ec = elfBufferOrErr.getError()) {
    llvm::errs() << elfPath << ": " << ec.message() << "\n";
    return 1;
  }

  std::string errorMessage;
  auto outFile = mlir::openOutputFile(outputFilename, &errorMessage);
  if (!outFile) {
    llvm::errs() << errorMessage << "\n";
    return 1;
  }

  if (auto err = qcc::convertElfToMem(**elfBufferOrErr, outFile->os())) {
    llvm::errs() << elfPath << ": " << llvm::toString(std::move(err)) << "\n";
    return 1;
  }

  outFile->keep();
  return 0;
}

} // namespace

int main(int argc, char** argv) {
  mlir::registerMLIRContextCLOptions();
  mlir::registerPassManagerCLOptions();
  mlir::registerDefaultTimingManagerCLOptions();

  const cl::opt<std::string> inputFilename(cl::Positional, cl::desc("Input-file"), cl::Required, cl::cat(qccCategory));
  const cl::opt<std::string> outputFilename("o", cl::desc("Output-file"), cl::value_desc("filename"), cl::init("-"),
                                            cl::cat(qccCategory));
  const cl::opt<Target> target("target", cl::desc("Target pipeline to compile for"), cl::init(Target::Qir),
                               cl::values(clEnumValN(Target::Qir, "qir", "QIR (LLVM-based) target"),
                                          clEnumValN(Target::HisepQ, "hisep-q", "HiSEP-Q QISA target")),
                               cl::cat(qccCategory));
  const cl::opt<Stage> compileTo(
      "compile-to", cl::desc("Stage to lower to and emit"), cl::init(Stage::LlvmIr),
      cl::values(
          clEnumValN(Stage::Mlir, "mlir", "MLIR in the LLVM dialect"),
          clEnumValN(Stage::LlvmIr, "ll", "LLVM IR: QIR for the QIR target and intrinsics for the HiSEP-Q target"),
          clEnumValN(Stage::LlvmIr, "llvmir", "alias for .ll"),
          clEnumValN(Stage::Assembly, "s", "Assembly output (requires --target=hisep-q)"),
          clEnumValN(Stage::Assembly, "assembly", "alias for .s"),
          clEnumValN(Stage::Object, "o", "Object file output (requires --target=hisep-q)"),
          clEnumValN(Stage::Object, "object", "alias for .o"),
          clEnumValN(Stage::Elf, "elf", "Linked ELF image, via hisepq.ld (requires --target=hisep-q)"),
          clEnumValN(Stage::Mem, "mem",
                     "Verilog $readmemh memory file, ready for the HiSEP-Q simulator (requires --target=hisep-q)")),
      cl::cat(qccCategory));
  const cl::opt<std::string> mtriple(
      "mtriple", cl::desc("Target triple for native code generation (default: riscv32-unknown-unknown for hisep-q)"),
      cl::init(""), cl::cat(qccCategory));
  const cl::opt<std::string> mattr(
      "mattr", cl::desc("Target attributes for native code generation (default: +experimental-xqv for hisep-q)"),
      cl::init(""), cl::cat(qccCategory));
  const cl::opt<std::string> linker(
      "linker", cl::desc("Linker to invoke for --compile-to=elf/mem (default: ld.lld, resolved via PATH)"),
      cl::init("ld.lld"), cl::cat(qccCategory));

  cl::ParseCommandLineOptions(argc, argv, "qcc - quantum compiler collection\n");

  mlir::DialectRegistry registry;

  // Register all builtin dialects and their extensions/interfaces:
  mlir::registerAllDialects(registry);

  // Our dialects:
  registry.insert<jasp::JaspDialect, mlir::qc::QCDialect, qcc::aux::AuxDialect>();

  // Register the specific interface implementations for the pipeline
  // Note: OneShotBufferize requires these for the "Standard" dialects
  mlir::arith::registerBufferizableOpInterfaceExternalModels(registry);
  mlir::linalg::registerBufferizableOpInterfaceExternalModels(registry);
  mlir::scf::registerBufferizableOpInterfaceExternalModels(registry);
  mlir::tensor::registerBufferizableOpInterfaceExternalModels(registry);
  mlir::bufferization::func_ext::registerBufferizableOpInterfaceExternalModels(registry);
  mlir::memref::registerAllocationOpInterfaceExternalModels(registry);
  mlir::func::registerInlinerExtension(registry);

  // For emitting LLVM IR:
  mlir::registerBuiltinDialectTranslation(registry);
  mlir::registerLLVMDialectTranslation(registry);

  mlir::MLIRContext context(registry);

  std::string errorMessage;
  auto inFile = mlir::openInputFile(inputFilename, &errorMessage);
  if (!inFile) {
    llvm::errs() << errorMessage << "\n";
    return 1;
  }

  llvm::SourceMgr sourceMgr;
  sourceMgr.AddNewSourceBuffer(std::move(inFile), llvm::SMLoc());

  // Enable nice diagnostic printing for parser and pass errors
  const mlir::SourceMgrDiagnosticHandler diagnosticHandler(sourceMgr, &context);

  mlir::OwningOpRef<mlir::ModuleOp> module = mlir::parseSourceFile<mlir::ModuleOp>(sourceMgr, &context);
  if (!module) {
    return 1;
  }

  mlir::PassManager pm(&context);
  if (mlir::failed(mlir::applyPassManagerCLOptions(pm))) {
    return 1;
  }
  qcc::buildQuantumPipeline(pm, {.target = target, .stage = compileTo});

  if (mlir::failed(pm.run(*module))) {
    return 1;
  }

  if (compileTo == Stage::Elf || compileTo == Stage::Mem) {
    if (target != Target::HisepQ) {
      llvm::errs() << "error: --compile-to=elf/mem requires --target=hisep-q\n";
      return 1;
    }
    return compileToElfOrMem(*module, compileTo, outputFilename, mtriple, mattr, linker);
  }

  auto outFile = mlir::openOutputFile(outputFilename, &errorMessage);
  if (!outFile) {
    llvm::errs() << errorMessage << "\n";
    return 1;
  }

  switch (compileTo) {
  case Stage::Mlir:
    module->print(outFile->os());
    break;
  case Stage::LlvmIr:
  case Stage::Assembly:
  case Stage::Object: {
    llvm::LLVMContext llvmContext;
    std::unique_ptr<llvm::Module> llvmModule = mlir::translateModuleToLLVMIR(*module, llvmContext);
    if (!llvmModule) {
      llvm::errs() << "failed to translate the module to LLVM IR\n";
      return 1;
    }

    if (compileTo == Stage::LlvmIr) {
      llvmModule->print(outFile->os(), /*AAW=*/nullptr);
      break;
    }

    auto fileType =
        (compileTo == Stage::Object) ? llvm::CodeGenFileType::ObjectFile : llvm::CodeGenFileType::AssemblyFile;
    auto& os = static_cast<llvm::raw_pwrite_stream&>(outFile->os());

    switch (target) {
    case Target::HisepQ: {
      std::unique_ptr<llvm::TargetMachine> targetMachine = createHisepQTargetMachine(*llvmModule, mtriple, mattr);
      if (!targetMachine) {
        return 1;
      }
      if (!emitNativeFile(*llvmModule, *targetMachine, fileType, os)) {
        return 1;
      }
      break;
    }
    case Target::Qir:
      llvm::errs() << "error: assembly/object output is not supported for --target=qir\n";
      return 1;
    }
    break;
  }
  case Stage::Elf:
  case Stage::Mem:
    llvm_unreachable("handled above");
  }

  outFile->keep(); // otherwise file gets deleted

  return 0;
}
