name: CI
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  change-detection:
    name: 🔍 Change
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-change-detection.yml@afe75175d32177a7291bbb7bd11b3276f60fc810 # v1.17.15

  cpp-tests-ubuntu:
    name: 🇨‌ Test 🐧
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests) && !contains(github.event.pull_request.labels.*.name, 'extensive-cpp-ci')
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-arm]
        config: [Release]
        include:
          - runs-on: ubuntu-24.04
            config: Debug
    uses: ./.github/workflows/reusable-mlir-tests-ubuntu.yml
    with:
      runs-on: ${{ matrix.runs-on }}
      config: ${{ matrix.config }}

  cpp-linter:
    name: 🇨‌ Lint
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-linter)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-linter.yml@afe75175d32177a7291bbb7bd11b3276f60fc810 # v1.17.15
    with:
      clang-version: 22
      build-project: true
      files-changed-only: false
      cpp-linter-extra-args: "-std=c++20"
      setup-mlir: true
      llvm-version: 22.1.0

  # this job does nothing and is only used for branch protection
  required-checks-pass:
    name: 🚦 Check
    if: always()
    needs:
      - change-detection
      - cpp-tests-ubuntu
      - cpp-linter
    runs-on: ubuntu-slim
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          allowed-skips: >-
            ${{
              fromJSON(needs.change-detection.outputs.run-cpp-tests)
              && '' || 'cpp-tests-ubuntu,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-cpp-tests)
              && '' || 'cpp-coverage,'
            }}
          jobs: ${{ toJSON(needs) }}
