name: 🐉 • Tests • Ubuntu
on:
  workflow_call:
    inputs:
      runs-on:
        description: >
          The Ubuntu runner image to use. Defaults to 'ubuntu-24.04'.
          This can be any valid Ubuntu runner image, such as 'ubuntu-24.04' or its ARM variant 'ubuntu-24.04-arm'.
        default: "ubuntu-24.04"
        type: string
      config:
        description: >
          The build type to use. Defaults to 'Release'.
          This can be any valid CMake build type, such as 'Debug' or 'Release'.
        default: "Release"
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-cpp-tests-${{ inputs.runs-on }}-${{ inputs.compiler }}-${{ inputs.config }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  mlir-tests-ubuntu:
    name: 🐧 ${{ inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up MLIR
        uses: munich-quantum-software/setup-mlir@f3ebc0bd966545a052741bc2b31750c34a09aa22 # v1.3.0
        with:
          llvm-version: 22.1.0

      - name: Set up mold as linker
        uses: rui314/setup-mold@725a8794d15fc7563f59595bd9556495c0564878 # v1

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          python-version: 3.13
          activate-environment: true
          enable-cache: false

      - name: Install Ninja
        run: uv tool install ninja

      - name: Install lit
        run: uv pip install lit

      - name: Configure CMake
        env:
          CONFIG: ${{ inputs.config }}
        run: |
          cmake -G Ninja -S . -B build \
            -DCMAKE_BUILD_TYPE=$CONFIG \
            -DLLVM_EXTERNAL_LIT=$(which lit)

      - name: Run lit tests
        env:
          CONFIG: ${{ inputs.config }}
        run: cmake --build build --config $CONFIG --target test-qcc-project
